### ISSUE TITLE
私にadmin権限は設定されていますでしょうか?

### ISSUE THREAD

**Issue by joemphilips** [naist-cl-parsing/julia-doc-ja#4]
circleCi側から連携ができないので、おそらくこのリポジトリのadmin権限が私に必要なのではないかとおもいます。
setting -> Collaborators & teams から自分の権限の状態が見れないのですが、 @hshindo さんからはどのように見えますか？

**Comment by hshindo** [comment]
Adminとしてcollaboratorに設定されています。

**Comment by hshindo** [comment]
うまくいかないよいでしたら、こちらからcircleciの設定をしてみましょうか？travisしか経験がありませんが。

**Comment by joemphilips** [comment]
ありがとうございます。うーん[add-projectsのページ](https://circleci.com/add-projects)からbuild projectで連携が開始するはずなのですが、ロード画面から一向に変化がないですね。

可能でしたら、私と同じことを試し、連携できるか見ていただけると助かります。

それでも解決しない場合`circle.yml` に文法ミスがあるか、CircleCi側に問題が発生しているかだと思います。

**Comment by hshindo** [comment]
ではbuild projectを試してみます

**Comment by joemphilips** [comment]
ありがとうございます。
考えてみたら private repoではないので、ビルド結果のhtmlを閲覧する機能があるのならTravisでも良いですね。

**Comment by hshindo** [comment]
build projectのボタンを押しても，ロード中から変化がないですね．
travisにしますか？

**Comment by joemphilips** [comment]
やはりそうですか。
[公式が推奨するように](https://circleci.com/docs/manually/) masterにからの`circle.yml` を追加したりしてみましたが変化がありません。
単純に公式が不安定なのだと思います。(以前からたまにこういうことがありました。werckerCI に比べるとマシなのですが。CIサービスにはこういう事態がつきもののようです。) 
travisにしましょう。使ったことがないので調べてみます。

**Comment by joemphilips** [comment]
travisを使用して始めたのでcloseします。
